#docker run -d --rm -name mango -p 27018:27917 -v mongodbdata:/db/data mong

version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo2
    ports:
       - 27018:27017
    volumes:
        - mongodbdata2:/data/db

volumes:
    mongodbdata2: